apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    app: devops-project
spec:
  selector:
    app: devops-project
  type: NodePort
  ports: 
    - nodePort: 31200
      port: 8080
      targetPort: 8080